import type { Journey } from "./data/journeys";

export const mitoJourney = {
  slug: "mito-oarai",
  number: "08",
  prefecture: "茨城県",
  title: "水戸・大洗",
  area: "水戸市・大洗町",
  date: "2026.07.27 — 07.28",
  duration: "1泊2日",
  year: 2026,
  totalCost: 31117,
  image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2200&q=88",
  bestPhoto: "千波湖の夕景セルフィー",
  bestFood: "らぁ麺ふじ田｜特製塩らぁ麺",
  bestPlace: "神磯の鳥居",
} satisfies Partial<Journey> & Pick<Journey, "slug" | "number" | "prefecture" | "title" | "area" | "date" | "duration" | "year" | "totalCost" | "image">;

export const prefectureRegions = [
  { name: "北海道", region: "北海道", x: 82, y: 5 },
  { name: "青森県", region: "東北", x: 78, y: 18 },
  { name: "岩手県", region: "東北", x: 83, y: 26 },
  { name: "宮城県", region: "東北", x: 81, y: 36 },
  { name: "秋田県", region: "東北", x: 73, y: 27 },
  { name: "山形県", region: "東北", x: 73, y: 37 },
  { name: "福島県", region: "東北", x: 76, y: 47 },
  { name: "茨城県", region: "関東", x: 78, y: 60 },
  { name: "栃木県", region: "関東", x: 70, y: 55 },
  { name: "群馬県", region: "関東", x: 62, y: 55 },
  { name: "埼玉県", region: "関東", x: 68, y: 63 },
  { name: "千葉県", region: "関東", x: 79, y: 68 },
  { name: "東京都", region: "関東", x: 69, y: 70 },
  { name: "神奈川県", region: "関東", x: 65, y: 75 },
  { name: "新潟県", region: "中部", x: 59, y: 44 },
  { name: "富山県", region: "中部", x: 48, y: 54 },
  { name: "石川県", region: "中部", x: 40, y: 52 },
  { name: "福井県", region: "中部", x: 39, y: 62 },
  { name: "山梨県", region: "中部", x: 58, y: 69 },
  { name: "長野県", region: "中部", x: 56, y: 58 },
  { name: "岐阜県", region: "中部", x: 47, y: 64 },
  { name: "静岡県", region: "中部", x: 57, y: 77 },
  { name: "愛知県", region: "中部", x: 48, y: 73 },
  { name: "三重県", region: "近畿", x: 40, y: 77 },
  { name: "滋賀県", region: "近畿", x: 38, y: 68 },
  { name: "京都府", region: "近畿", x: 32, y: 66 },
  { name: "大阪府", region: "近畿", x: 31, y: 74 },
  { name: "兵庫県", region: "近畿", x: 24, y: 69 },
  { name: "奈良県", region: "近畿", x: 36, y: 76 },
  { name: "和歌山県", region: "近畿", x: 31, y: 84 },
  { name: "鳥取県", region: "中国", x: 18, y: 64 },
  { name: "島根県", region: "中国", x: 8, y: 65 },
  { name: "岡山県", region: "中国", x: 19, y: 72 },
  { name: "広島県", region: "中国", x: 10, y: 74 },
  { name: "山口県", region: "中国", x: 1, y: 77 },
  { name: "徳島県", region: "四国", x: 24, y: 87 },
  { name: "香川県", region: "四国", x: 19, y: 80 },
  { name: "愛媛県", region: "四国", x: 11, y: 86 },
  { name: "高知県", region: "四国", x: 16, y: 94 },
  { name: "福岡県", region: "九州", x: -3, y: 88 },
  { name: "佐賀県", region: "九州", x: -9, y: 93 },
  { name: "長崎県", region: "九州", x: -15, y: 97 },
  { name: "熊本県", region: "九州", x: -5, y: 101 },
  { name: "大分県", region: "九州", x: 3, y: 96 },
  { name: "宮崎県", region: "九州", x: 1, y: 108 },
  { name: "鹿児島県", region: "九州", x: -7, y: 111 },
  { name: "沖縄県", region: "沖縄", x: -16, y: 116 },
] as const;

